SELECT * FROM паспортные_данные;
SELECT Дата_рождения FROM паспортные_данные;
SELECT Дата_рождения, Фамилия FROM паспортные_данные;
SELECT * FROM паспортные_данные ORDER BY Фамилия;
SELECT * FROM паспортные_данные ORDER BY Фамилия DESC;
SELECT * FROM паспортные_данные ORDER BY Фамилия, Имя;
SELECT * FROM паспортные_данные WHERE Имя='Андрей';
SELECT * FROM паспортные_данные WHERE Имя IS NOT NULL;
SELECT * FROM паспортные_данные WHERE Код_паспорта BETWEEN 5 AND 8;
SELECT * FROM паспортные_данные WHERE Код_паспорта IN (5, 8);
SELECT * FROM паспортные_данные WHERE Фамилия LIKE '%ов';
ALTER TABLE книга ADD COLUMN картинка TEXT;
