-- MySQL Script generated by MySQL Workbench
-- Wed Dec  8 06:46:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bib` DEFAULT CHARACTER SET latin1 ;
USE `bib` ;

-- -----------------------------------------------------
-- Table `bib`.`паспортные_данные`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`паспортные_данные` (
  `Код_паспорта` INT(11) NOT NULL AUTO_INCREMENT,
  `Фамилия` MEDIUMTEXT NULL DEFAULT NULL,
  `Имя` MEDIUMTEXT NULL DEFAULT NULL,
  `Отчество` MEDIUMTEXT NULL DEFAULT NULL,
  `Серия` INT(11) NULL DEFAULT NULL,
  `Номер` INT(11) NULL DEFAULT NULL,
  `Дата_рождения` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Код_паспорта`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`пользователь`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`пользователь` (
  `Код_пользователя` INT(11) NOT NULL AUTO_INCREMENT,
  `Код_паспорта` INT(11) NOT NULL,
  `Имя_пользователя` MEDIUMTEXT NULL DEFAULT NULL,
  `Пароль` MEDIUMTEXT NULL DEFAULT NULL,
  `Телефон` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Код_пользователя`),
  INDEX `R_22` (`Код_паспорта` ASC) VISIBLE,
  CONSTRAINT `пользователь_ibfk_1`
    FOREIGN KEY (`Код_паспорта`)
    REFERENCES `bib`.`паспортные_данные` (`Код_паспорта`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`читатель`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`читатель` (
  `Код_пользователя` INT(11) NOT NULL,
  `Дата_регистрации` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Код_пользователя`),
  CONSTRAINT `читатель_ibfk_1`
    FOREIGN KEY (`Код_пользователя`)
    REFERENCES `bib`.`пользователь` (`Код_пользователя`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`библиотекарь`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`библиотекарь` (
  `Код_пользователя` INT(11) NOT NULL,
  `Дата_регистрации` DATE NULL DEFAULT NULL,
  `Почтовый_адрес` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Код_пользователя`),
  CONSTRAINT `библиотекарь_ibfk_1`
    FOREIGN KEY (`Код_пользователя`)
    REFERENCES `bib`.`пользователь` (`Код_пользователя`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`абонемент`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`абонемент` (
  `Код_абонемента` INT(11) NOT NULL AUTO_INCREMENT,
  `Читателя` INT(11) NULL DEFAULT NULL,
  `Библиотекаря` INT(11) NULL DEFAULT NULL,
  `Выговоры` INT(11) NULL DEFAULT NULL,
  `ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Код_абонемента`),
  INDEX `R_18` (`Читателя` ASC) VISIBLE,
  INDEX `R_34` (`Библиотекаря` ASC) VISIBLE,
  CONSTRAINT `абонемент_ibfk_1`
    FOREIGN KEY (`Читателя`)
    REFERENCES `bib`.`читатель` (`Код_пользователя`),
  CONSTRAINT `абонемент_ibfk_2`
    FOREIGN KEY (`Библиотекаря`)
    REFERENCES `bib`.`библиотекарь` (`Код_пользователя`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`тематика`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`тематика` (
  `Код_тематики` INT(11) NOT NULL AUTO_INCREMENT,
  `Название` MEDIUMTEXT NULL DEFAULT NULL,
  `Примечание` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Код_тематики`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`автор_пользователь`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`автор_пользователь` (
  `Код_пользователя` INT(11) NOT NULL,
  `Код_автора` INT(11) NULL DEFAULT NULL,
  `Почтовый_адрес` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Код_пользователя`),
  INDEX `R_44` (`Код_автора` ASC) VISIBLE,
  CONSTRAINT `автор_пользователь_ibfk_1`
    FOREIGN KEY (`Код_пользователя`)
    REFERENCES `bib`.`пользователь` (`Код_пользователя`)
    ON DELETE CASCADE,
  CONSTRAINT `автор_пользователь_ibfk_2`
    FOREIGN KEY (`Код_автора`)
    REFERENCES `bib`.`автор_по_книгам` (`Код_автора`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`администратор`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`администратор` (
  `Код_пользователя` INT(11) NOT NULL,
  `Дата_регистрации` DATE NULL DEFAULT NULL,
  `Почтовый_адрес` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Код_пользователя`),
  CONSTRAINT `администратор_ibfk_1`
    FOREIGN KEY (`Код_пользователя`)
    REFERENCES `bib`.`пользователь` (`Код_пользователя`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`книга`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`книга` (
  `Код_книги` INT(11) NOT NULL AUTO_INCREMENT,
  `Название` MEDIUMTEXT NULL DEFAULT NULL,
  `Издательство` MEDIUMTEXT NULL DEFAULT NULL,
  `Год_издания` INT(11) NULL DEFAULT NULL,
  `Код_тематики` INT(11) NULL DEFAULT NULL,
  `Администратор` INT(11) NULL DEFAULT NULL,
  `Автор` INT(11) NULL DEFAULT NULL,
  `ID` INT(11) NULL DEFAULT NULL,
  `картинка` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Код_книги`),
  INDEX `R_17` (`Код_тематики` ASC) VISIBLE,
  INDEX `R_19` (`Автор` ASC) VISIBLE,
  INDEX `R_30` (`Администратор` ASC) VISIBLE,
  CONSTRAINT `книга_ibfk_1`
    FOREIGN KEY (`Код_тематики`)
    REFERENCES `bib`.`тематика` (`Код_тематики`),
  CONSTRAINT `книга_ibfk_2`
    FOREIGN KEY (`Автор`)
    REFERENCES `bib`.`автор_пользователь` (`Код_пользователя`),
  CONSTRAINT `книга_ibfk_3`
    FOREIGN KEY (`Администратор`)
    REFERENCES `bib`.`администратор` (`Код_пользователя`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`автор_по_книгам`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`автор_по_книгам` (
  `Код_автора` INT(11) NOT NULL AUTO_INCREMENT,
  `Фамилия` MEDIUMTEXT NULL DEFAULT NULL,
  `Имя` MEDIUMTEXT NULL DEFAULT NULL,
  `Отчество` MEDIUMTEXT NULL DEFAULT NULL,
  `Дата_рождения` DATE NULL DEFAULT NULL,
  `Инициалы` MEDIUMTEXT NULL DEFAULT NULL,
  `книга_Код_книги` INT(11) NOT NULL,
  PRIMARY KEY (`Код_автора`),
  INDEX `fk_автор_по_книгам_книга1_idx` (`книга_Код_книги` ASC) VISIBLE,
  CONSTRAINT `fk_автор_по_книгам_книга1`
    FOREIGN KEY (`книга_Код_книги`)
    REFERENCES `bib`.`книга` (`Код_книги`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`заказанная_книга`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`заказанная_книга` (
  `Отметка_о_возврате` MEDIUMTEXT NULL DEFAULT NULL,
  `Дата_возврата` DATE NULL DEFAULT NULL,
  `Фактическая_дата_возврата` DATE NULL DEFAULT NULL,
  `Код_пользователя` INT(11) NULL DEFAULT NULL,
  `Код_книги` INT(11) NOT NULL,
  PRIMARY KEY (`Код_книги`),
  INDEX `R_32` (`Код_пользователя` ASC) VISIBLE,
  CONSTRAINT `заказанная_книга_ibfk_1`
    FOREIGN KEY (`Код_пользователя`)
    REFERENCES `bib`.`библиотекарь` (`Код_пользователя`),
  CONSTRAINT `заказанная_книга_ibfk_2`
    FOREIGN KEY (`Код_книги`)
    REFERENCES `bib`.`книга` (`Код_книги`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bib`.`заказ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bib`.`заказ` (
  `Код_заказа` INT(11) NOT NULL AUTO_INCREMENT,
  `Дата_заказа` DATE NULL DEFAULT NULL,
  `Код_абонемента` INT(11) NULL DEFAULT NULL,
  `Код_книги` INT(11) NULL DEFAULT NULL,
  `ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Код_заказа`),
  INDEX `R_47` (`Код_абонемента` ASC) VISIBLE,
  INDEX `R_53` (`Код_книги` ASC) VISIBLE,
  CONSTRAINT `заказ_ibfk_1`
    FOREIGN KEY (`Код_абонемента`)
    REFERENCES `bib`.`абонемент` (`Код_абонемента`),
  CONSTRAINT `заказ_ibfk_2`
    FOREIGN KEY (`Код_книги`)
    REFERENCES `bib`.`заказанная_книга` (`Код_книги`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
